[package]
name = "buscaluso"
version = "0.1.0"
authors = ["Daniel Getz <dan@getzit.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
